name: school_of_future
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  injectable: ^2.4.2
  http: ^1.2.1
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.3
  location: ^7.0.0
  geocoding: ^3.0.0
  cached_network_image: ^3.3.1
  device_info_plus: ^9.1.2
  in_app_update: ^4.2.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  gap: ^3.0.1
  easy_localization: ^3.0.7
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3
  html2md: ^1.3.2
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.15.1
  package_info_plus: ^8.0.1
  file_picker: ^8.0.3
  webview_flutter: ^4.8.0
  flutter_quill: ^9.2.3
  quill_json_to_html: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/feature_icons/
    - assets/images/feature_icons_svg/
    - assets/images/subject_images_svgs/
    # - assets/lottie/
    # - assets/translations/
    # - assets/webpages/
    - assets/images/svg/
    - lib/core/translations/
    - .env
    - .env.profile
    - .env.release

  fonts:
    - family: solaimanlipi
      fonts:
        - asset: assets/fonts/solaimanlipi/solaimanlipi-regular.ttf
          weight: 400
        - asset: assets/fonts/solaimanlipi/solaimanlipi-bold.ttf
          weight: 800

    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/ubuntu-regular.ttf
        - asset: assets/fonts/ubuntu/ubuntu-light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/ubuntu-medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/ubuntu-bold.ttf
          weight: 700
