name: flutter_module
description: "A new Flutter module project."

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  injectable: ^2.4.2
  http: ^1.2.1
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.3
  location: ^7.0.0
  geocoding: ^3.0.0
  cached_network_image: ^3.3.1
  device_info_plus: ^9.1.2
  in_app_update: ^4.2.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  gap: ^3.0.1
  easy_localization: ^3.0.7
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3
  html2md: ^1.3.2
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.15.1
  package_info_plus: ^8.0.1
  file_picker: ^8.0.3
  webview_flutter: ^4.8.0
  flutter_quill: ^10.5.17
  quill_json_to_html: ^1.0.1
  flutter_quill_delta_from_html: ^1.4.1
  flutter_datetime_picker_plus: ^2.2.0
  table_calendar: ^3.1.2
  dropdown_textfield: ^1.2.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.12.0
  change_app_package_name: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/feature_icons/
    - assets/images/feature_icons_svg/
    - assets/images/subject_images_svgs/
    # - assets/lottie/
    # - assets/translations/
    # - assets/webpages/
    - assets/images/svg/
    - lib/core/translations/
    - .env
    - .env.profile
    - .env.release

  fonts:
    - family: solaimanlipi
      fonts:
        - asset: assets/fonts/solaimanlipi/solaimanlipi-regular.ttf
          weight: 400
        - asset: assets/fonts/solaimanlipi/solaimanlipi-bold.ttf
          weight: 800

    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/ubuntu-regular.ttf
        - asset: assets/fonts/ubuntu/ubuntu-light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/ubuntu-medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/ubuntu-bold.ttf
          weight: 700

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
